Fix typo
Project-Sloth/ps-dispatch pull request #150
Opened 2023-05-16 05:21 UTC by BackSH00TER

- Fixed typo from `InjuriedPerson` to `InjuredPerson`
- Moved default hunting zone from middle of LSIA to in the county by the river
  
![image](https://github.com/Project-Sloth/ps-dispatch/assets/18689469/56285995-f4b9-467d-b129-fe31e3c15cb9)

- Fixed the first responder check in `togglealerts`

2023-05-16 19:53 UTC, ADRNALN approved these changes

2023-06-27 23:45 UTC, Z3rio commented on server/sv_main.lua
>  	end
```suggestion
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    if Config.AuthorizedJobs.FirstResponder.Check(Player.PlayerData) then
        TriggerClientEvent('dispatch:manageNotifs', src, args[1])
    end
```

resolve linting

2023-08-11 07:18 UTC, xFutte requested changes

2023-08-11 07:18 UTC, xFutte commented on README.md
> +- exports['ps-dispatch']:InjuredPerson()
This breaks backward compitability
```suggestion
- exports['ps-dispatch']:InjuriedPerson()
```

2023-08-11 07:18 UTC, xFutte commented on client/cl_eventhandlers.lua
> +    if not Config.AuthorizedJobs.FirstResponder.Check() then exports['ps-dispatch']:InjuredPerson() end
Breaks backward compatibility. Revert.
```suggestion
    if not Config.AuthorizedJobs.FirstResponder.Check() then exports['ps-dispatch']:InjuriedPerson() end
```

2023-08-11 07:18 UTC, xFutte commented on client/cl_events.lua
> +local function InjuredPerson()
```suggestion
local function InjuriedPerson()

```

2023-08-11 07:18 UTC, xFutte commented on client/cl_events.lua
> +exports('InjuredPerson', InjuredPerson)
```suggestion
exports('InjuriedPerson', InjuriedPerson)

```

2023-08-11 07:19 UTC, xFutte commented
Changing the export name will break backward compatibility. Since this resource has been around for a while, we can't simply do this change in a minor version. If we wish to do so, we need to make a new major release.

2023-10-09 20:57 UTC, closed without merging

2023-10-16 20:31 UTC, adamdrakon commented
> Changing the export name will break backward compatibility. Since this resource has been around for a while, we can't simply do this change in a minor version. If we wish to do so, we need to make a new major release.

Not hugely important, but could add `exports('InjuredPerson', InjuriedPerson)`, but then, so too could anyone else add it on their own end.