Fixing 3 Different Errors
Project-Sloth/ps-dispatch pull request #284
Opened 2024-07-09 17:06 UTC by valentineu0

## 01. Parameter Inaccuracy in Humane Labs Translations
The Humane Labs translation parameter to all language files was treated as "humanerobbery", but the parameter to **alerts.lua** was different. Parameters in all language translations have been changed.

#### Before (In Use)
https://github.com/Project-Sloth/ps-dispatch/blob/ece5b7e79b9cfbf1a121bb28c5de337f43728e0a/client/alerts.lua#L629
https://github.com/Project-Sloth/ps-dispatch/blob/ece5b7e79b9cfbf1a121bb28c5de337f43728e0a/locales/en.json#L79

#### Fixed (All Languages)
![image](https://github.com/Project-Sloth/ps-dispatch/assets/78941156/f5383932-7f8f-4b7b-90ac-cd4b27730357)

## 02. Re-evaluation of Turkish Language Support
The Turkish translation has been changed again, spelling errors have been eliminated and it has been made more understandable.

## 03. README
Fixed a spelling error noticed in the README.

2024-07-09 17:13 UTC, valentineu0 commented
Changing the part in **/client/alerts.lua** that I wrote in error **01** could have been a shorter method, but it seemed more meaningful to write the exact name of the robbery, so I did it on purpose.

2024-07-10 21:58 UTC, xFutte requested changes

2024-07-10 21:58 UTC, xFutte commented on README.md
> -- exports['ps-dispatch']:HumaneRobery()
Unfortunately, this change is backward incompatible and will break scripts that rely on this export if they upgrade to a newer version. We can't rename this unless we make a new major release. Please revert this change.

2024-07-10 22:00 UTC, xFutte approved these changes
LGTM!

2024-07-10 22:01 UTC, merged